run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true
  gofmt:
    simplify: true
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
  gosec:
    excludes:
      - G104 # Audit errors not checked - we handle this with errcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
