# Codecov configuration for azd-rest
# See: https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false

    patch:
      default:
        target: 50%
        threshold: 10%
        informational: true

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  hide_project_coverage: false

ignore:
  - "cli/src/cmd/rest/main.go"
  - "**/generated/**"
  - "**/*_test.go"

flags:
  unittests:
    paths:
      - cli/src/
    carryforward: true
